# =========================================================
# 03_GSE5281_region_MTG_analysis.R
# Purpose:
# Perform MTG-focused within-region analysis in GSE5281.
# This script generates MTG AD high/low subgroup metadata,
# PCA source data, and MTG high-vs-low limma results.
# =========================================================

source("scripts/00_setup.R")

# -------------------------
# Required packages
# -------------------------
suppressPackageStartupMessages({
  library(limma)
  library(ggplot2)
})

# -------------------------
# Input files generated by 02_project_signature_GSE5281.R
# -------------------------
score_file <- file.path(dir_tables, "GSE5281_EpilepsyScore_top100.csv")
expr_file <- file.path(dir_tables, "GSE5281_gene_level_expression_matrix.csv")

required_files <- c(score_file, expr_file)
missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Missing required input files:\n",
    paste(missing_files, collapse = "\n"),
    "\nPlease run 02_project_signature_GSE5281.R first."
  )
}

# -------------------------
# Step 1. Read score table and gene-level expression matrix
# -------------------------
score_df <- read.csv(
  score_file,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

expr_df <- read.csv(
  expr_file,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

required_score_cols <- c("Sample", "Diagnosis", "BrainRegion", "EpilepsyScore")
missing_score_cols <- setdiff(required_score_cols, colnames(score_df))

if (length(missing_score_cols) > 0) {
  stop(
    "Score table is missing required columns: ",
    paste(missing_score_cols, collapse = ", ")
  )
}

if (!"Gene" %in% colnames(expr_df)) {
  stop("Expression matrix must contain a first column named 'Gene'.")
}

# -------------------------
# Step 2. Prepare expression matrix
# -------------------------
expr_gene <- as.matrix(expr_df[, setdiff(colnames(expr_df), "Gene"), drop = FALSE])
rownames(expr_gene) <- toupper(trimws(expr_df$Gene))
mode(expr_gene) <- "numeric"

score_df$Sample <- trimws(as.character(score_df$Sample))
score_df$Diagnosis <- trimws(as.character(score_df$Diagnosis))
score_df$BrainRegion <- trimws(as.character(score_df$BrainRegion))

# -------------------------
# Step 3. Extract MTG AD samples
# -------------------------
mtg_ad <- subset(
  score_df,
  BrainRegion == "MTG" & Diagnosis == "AD"
)

if (nrow(mtg_ad) < 4) {
  stop("Too few MTG AD samples found for within-region analysis.")
}

missing_samples <- setdiff(mtg_ad$Sample, colnames(expr_gene))
if (length(missing_samples) > 0) {
  stop(
    "The following MTG AD samples are missing from expression matrix:\n",
    paste(missing_samples, collapse = ", ")
  )
}

# Reorder samples
expr_mtg_ad <- expr_gene[, mtg_ad$Sample, drop = FALSE]
mtg_ad <- mtg_ad[match(colnames(expr_mtg_ad), mtg_ad$Sample), ]

stopifnot(all(colnames(expr_mtg_ad) == mtg_ad$Sample))

# -------------------------
# Step 4. Define MTG high/low subgroups by regional median
# -------------------------
median_cut <- median(mtg_ad$EpilepsyScore, na.rm = TRUE)

mtg_ad$HighLow <- ifelse(
  mtg_ad$EpilepsyScore >= median_cut,
  "High",
  "Low"
)

mtg_ad$HighLow <- factor(mtg_ad$HighLow, levels = c("Low", "High"))

write.csv(
  mtg_ad,
  file = file.path(dir_tables, "GSE5281_MTG_AD_high_low_metadata.csv"),
  row.names = FALSE
)

# Summary table
mtg_summary <- aggregate(
  EpilepsyScore ~ HighLow,
  data = mtg_ad,
  function(x) {
    c(
      n = length(x),
      mean = mean(x, na.rm = TRUE),
      median = median(x, na.rm = TRUE),
      sd = sd(x, na.rm = TRUE),
      min = min(x, na.rm = TRUE),
      max = max(x, na.rm = TRUE)
    )
  }
)

mtg_summary <- do.call(data.frame, mtg_summary)

write.csv(
  mtg_summary,
  file = file.path(dir_tables, "GSE5281_MTG_AD_high_low_score_summary.csv"),
  row.names = FALSE
)

# -------------------------
# Step 5. PCA of MTG AD samples
# -------------------------
# Remove genes with zero variance or missing values
keep_genes <- apply(expr_mtg_ad, 1, function(x) {
  sum(!is.na(x)) > 1 && sd(x, na.rm = TRUE) > 0
})

expr_mtg_ad_pca <- expr_mtg_ad[keep_genes, , drop = FALSE]

pca_res <- prcomp(
  t(expr_mtg_ad_pca),
  scale. = TRUE
)

pca_var <- summary(pca_res)$importance[2, 1:2] * 100

pca_df <- data.frame(
  Sample = rownames(pca_res$x),
  PC1 = pca_res$x[, 1],
  PC2 = pca_res$x[, 2],
  stringsAsFactors = FALSE
)

pca_df <- merge(
  pca_df,
  mtg_ad[, c("Sample", "EpilepsyScore", "HighLow")],
  by = "Sample",
  all.x = TRUE
)

write.csv(
  pca_df,
  file = file.path(dir_figdata, "Figure4B_MTG_AD_PCA_source_data.csv"),
  row.names = FALSE
)

# -------------------------
# Step 6. Limma differential analysis: High vs Low
# -------------------------
group_mtg <- factor(mtg_ad$HighLow, levels = c("Low", "High"))

design_mtg <- model.matrix(~ 0 + group_mtg)
colnames(design_mtg) <- levels(group_mtg)

fit_mtg <- lmFit(expr_mtg_ad, design_mtg)

contrast_mtg <- makeContrasts(
  High - Low,
  levels = design_mtg
)

fit_mtg2 <- contrasts.fit(fit_mtg, contrast_mtg)
fit_mtg2 <- eBayes(fit_mtg2)

deg_mtg <- topTable(
  fit_mtg2,
  number = Inf,
  sort.by = "P"
)

deg_mtg$Gene <- rownames(deg_mtg)
deg_mtg <- deg_mtg[, c("Gene", setdiff(colnames(deg_mtg), "Gene"))]

write.csv(
  deg_mtg,
  file = file.path(dir_tables, "GSE5281_MTG_AD_high_vs_low_limma_results.csv"),
  row.names = FALSE
)

# -------------------------
# Step 7. Export source data for Figure 4A
# -------------------------
fig4a_source <- mtg_ad[, c("Sample", "EpilepsyScore", "HighLow")]

write.csv(
  fig4a_source,
  file = file.path(dir_figdata, "Figure4A_MTG_AD_high_low_source_data.csv"),
  row.names = FALSE
)

# -------------------------
# Step 8. Generate basic Figure 4A and Figure 4B plots
# -------------------------
p4a <- ggplot(
  mtg_ad,
  aes(x = HighLow, y = EpilepsyScore, fill = HighLow)
) +
  geom_boxplot(width = 0.6, outlier.shape = NA, color = "black") +
  geom_jitter(width = 0.12, size = 2.2, alpha = 0.85) +
  scale_fill_manual(values = c("Low" = "#F8766D", "High" = "#00BFC4")) +
  labs(
    x = "MTG AD subgroup",
    y = "EpilepsyScore"
  ) +
  theme_bw(base_size = 13) +
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank()
  )

ggsave(
  filename = file.path(dir_results, "Figure4A_MTG_AD_high_low_boxplot.png"),
  plot = p4a,
  width = 5.5,
  height = 4.5,
  dpi = 300
)

p4b <- ggplot(
  pca_df,
  aes(x = PC1, y = PC2, color = HighLow)
) +
  geom_point(size = 3) +
  scale_color_manual(values = c("Low" = "black", "High" = "#F8766D")) +
  labs(
    x = paste0("PC1 (", round(pca_var[1], 1), "%)"),
    y = paste0("PC2 (", round(pca_var[2], 1), "%)"),
    color = NULL
  ) +
  theme_bw(base_size = 13) +
  theme(
    panel.grid.minor = element_blank()
  )

ggsave(
  filename = file.path(dir_results, "Figure4B_MTG_AD_PCA.png"),
  plot = p4b,
  width = 5.8,
  height = 4.8,
  dpi = 300
)

# -------------------------
# Step 9. Export PCA correlations with EpilepsyScore
# -------------------------
pc_cor <- data.frame(
  Comparison = c(
    "EpilepsyScore vs PC1",
    "EpilepsyScore vs PC2"
  ),
  Spearman_rho = c(
    unname(cor.test(pca_df$EpilepsyScore, pca_df$PC1, method = "spearman")$estimate),
    unname(cor.test(pca_df$EpilepsyScore, pca_df$PC2, method = "spearman")$estimate)
  ),
  Spearman_P = c(
    cor.test(pca_df$EpilepsyScore, pca_df$PC1, method = "spearman")$p.value,
    cor.test(pca_df$EpilepsyScore, pca_df$PC2, method = "spearman")$p.value
  )
)

write.csv(
  pc_cor,
  file = file.path(dir_tables, "GSE5281_MTG_AD_PCA_correlation_with_EpilepsyScore.csv"),
  row.names = FALSE
)

message("GSE5281 MTG-focused analysis completed.")
