# =========================================================
# 06_MTG_continuous_synapse_glia_analysis.R
# Purpose:
# Evaluate whether EpilepsyScore is continuously associated
# with synaptic and glia-associated module scores in MTG AD samples.
#
# Outputs:
#   - Supplementary Figure S7 source data
#   - Supplementary Table S12
#   - Scatter plots for SynapseScore, GliaScore, and Synapse-Glia balance
# =========================================================

source("scripts/00_setup.R")

suppressPackageStartupMessages({
  library(ggplot2)
})

# -------------------------
# Input files generated by previous scripts
# -------------------------
score_file <- file.path(dir_tables, "GSE5281_EpilepsyScore_top100.csv")
expr_file <- file.path(dir_tables, "GSE5281_gene_level_expression_matrix.csv")

if (!file.exists(score_file)) {
  stop("Missing score file. Please run 02_project_signature_GSE5281.R first.")
}

if (!file.exists(expr_file)) {
  stop("Missing expression matrix. Please run 02_project_signature_GSE5281.R first.")
}

score_df <- read.csv(
  score_file,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

expr_df <- read.csv(
  expr_file,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

required_score_cols <- c("Sample", "Diagnosis", "BrainRegion", "EpilepsyScore")
missing_score_cols <- setdiff(required_score_cols, colnames(score_df))

if (length(missing_score_cols) > 0) {
  stop(
    "Score table is missing required columns: ",
    paste(missing_score_cols, collapse = ", ")
  )
}

if (!"Gene" %in% colnames(expr_df)) {
  stop("Expression matrix must contain a first column named 'Gene'.")
}

# -------------------------
# Prepare expression matrix
# -------------------------
expr_gene <- as.matrix(expr_df[, setdiff(colnames(expr_df), "Gene"), drop = FALSE])
rownames(expr_gene) <- toupper(trimws(expr_df$Gene))
mode(expr_gene) <- "numeric"

score_df$Sample <- trimws(as.character(score_df$Sample))
score_df$Diagnosis <- trimws(as.character(score_df$Diagnosis))
score_df$BrainRegion <- trimws(as.character(score_df$BrainRegion))

# -------------------------
# Extract MTG AD samples
# -------------------------
mtg_ad <- subset(
  score_df,
  BrainRegion == "MTG" & Diagnosis == "AD"
)

if (nrow(mtg_ad) < 4) {
  stop("Too few MTG AD samples found.")
}

missing_samples <- setdiff(mtg_ad$Sample, colnames(expr_gene))

if (length(missing_samples) > 0) {
  stop(
    "The following MTG AD samples are missing from expression matrix:\n",
    paste(missing_samples, collapse = ", ")
  )
}

expr_mtg_ad <- expr_gene[, mtg_ad$Sample, drop = FALSE]
mtg_ad <- mtg_ad[match(colnames(expr_mtg_ad), mtg_ad$Sample), ]

stopifnot(all(colnames(expr_mtg_ad) == mtg_ad$Sample))

# -------------------------
# Representative module gene sets
# -------------------------
# These genes correspond to representative synaptic- and glia-associated
# module genes used for continuous MTG module-score analysis.
#
# Users may replace these lists with their own curated module genes,
# provided that the same gene symbols are used consistently.

synapse_genes <- c(
  "STXBP5", "CADPS", "CACNA1B", "SLC4A8", "SYN1",
  "NCDN", "SYN3", "BSN", "KCNA2", "GABRB2",
  "PPP3CA", "GABRD", "GRIA3", "HOMER1", "STXBP1"
)

glia_genes <- c(
  "PTPRB", "IFNGR1", "PHGDH", "GPM6B", "RELA",
  "CARD8", "PLCG2", "STAT3", "ZC3HAV1",
  "HEG1", "FZD2", "SOX17", "TJP2", "EZR",
  "ANXA3", "ENG", "SMOC2", "TGFBR1", "ITGB1"
)

synapse_genes <- unique(toupper(synapse_genes))
glia_genes <- unique(toupper(glia_genes))

synapse_use <- intersect(synapse_genes, rownames(expr_mtg_ad))
glia_use <- intersect(glia_genes, rownames(expr_mtg_ad))

message("Matched synaptic module genes: ", length(synapse_use))
message("Matched glia-associated module genes: ", length(glia_use))

if (length(synapse_use) < 3) {
  stop("Too few matched synaptic module genes.")
}

if (length(glia_use) < 3) {
  stop("Too few matched glia-associated module genes.")
}

# -------------------------
# Module score function
# -------------------------
calc_module_score <- function(expr_mat, genes) {
  sub <- expr_mat[genes, , drop = FALSE]
  
  # Row-wise z-score across samples
  sub_z <- t(scale(t(sub)))
  
  # Remove genes with zero variance
  keep <- apply(sub_z, 1, function(x) !all(is.na(x)))
  sub_z <- sub_z[keep, , drop = FALSE]
  
  if (nrow(sub_z) == 0) {
    return(rep(NA_real_, ncol(expr_mat)))
  }
  
  colMeans(sub_z, na.rm = TRUE)
}

# -------------------------
# Calculate module scores
# -------------------------
module_df <- data.frame(
  Sample = mtg_ad$Sample,
  EpilepsyScore = mtg_ad$EpilepsyScore,
  stringsAsFactors = FALSE
)

module_df$SynapseScore <- calc_module_score(expr_mtg_ad, synapse_use)
module_df$GliaScore <- calc_module_score(expr_mtg_ad, glia_use)
module_df$SynGliaBalance <- module_df$SynapseScore - module_df$GliaScore

# Optional: define median-based high/low label for plotting
median_cut <- median(module_df$EpilepsyScore, na.rm = TRUE)
module_df$HighLow <- ifelse(
  module_df$EpilepsyScore >= median_cut,
  "High",
  "Low"
)

module_df$HighLow <- factor(module_df$HighLow, levels = c("Low", "High"))

write.csv(
  module_df,
  file = file.path(dir_figdata, "Supplementary_Figure_S7_source_data.csv"),
  row.names = FALSE
)

# Also export matched module genes
matched_module_genes <- rbind(
  data.frame(Module = "Synapse", Gene = synapse_use),
  data.frame(Module = "Glia-associated", Gene = glia_use)
)

write.csv(
  matched_module_genes,
  file = file.path(dir_tables, "MTG_continuous_analysis_matched_module_genes.csv"),
  row.names = FALSE
)

# -------------------------
# Correlation and regression analysis
# -------------------------
run_continuous_analysis <- function(df, y_col, label) {
  cor_res <- cor.test(
    df$EpilepsyScore,
    df[[y_col]],
    method = "spearman",
    exact = FALSE
  )
  
  fit <- lm(
    as.formula(paste0(y_col, " ~ EpilepsyScore")),
    data = df
  )
  
  sm <- summary(fit)$coefficients
  ci <- confint(fit)
  
  data.frame(
    Comparison = paste0("EpilepsyScore vs ", label),
    Spearman_rho = unname(cor_res$estimate),
    Spearman_P_value = cor_res$p.value,
    Linear_regression_beta = sm["EpilepsyScore", "Estimate"],
    Linear_regression_P_value = sm["EpilepsyScore", "Pr(>|t|)"],
    CI_lower_for_beta = ci["EpilepsyScore", 1],
    CI_upper_for_beta = ci["EpilepsyScore", 2],
    stringsAsFactors = FALSE
  )
}

s12_table <- rbind(
  run_continuous_analysis(module_df, "SynapseScore", "synaptic module score"),
  run_continuous_analysis(module_df, "GliaScore", "glia-associated module score"),
  run_continuous_analysis(module_df, "SynGliaBalance", "synapse-glia balance score")
)

write.csv(
  s12_table,
  file = file.path(dir_tables, "Supplementary_Table_S12_MTG_continuous_module_analysis.csv"),
  row.names = FALSE
)

# -------------------------
# Plotting function
# -------------------------
plot_continuous <- function(df, y_col, y_label, title_text, out_file) {
  p <- ggplot(
    df,
    aes(x = EpilepsyScore, y = .data[[y_col]])
  ) +
    geom_point(size = 2.6, alpha = 0.85) +
    geom_smooth(method = "lm", se = TRUE, color = "black", linewidth = 0.7) +
    labs(
      title = title_text,
      x = "EpilepsyScore",
      y = y_label
    ) +
    theme_bw(base_size = 13) +
    theme(
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5)
    )
  
  ggsave(
    filename = out_file,
    plot = p,
    width = 5.5,
    height = 4.5,
    dpi = 300
  )
  
  return(p)
}

p_syn <- plot_continuous(
  module_df,
  "SynapseScore",
  "Synaptic module score",
  "MTG AD: EpilepsyScore vs synaptic module score",
  file.path(dir_results, "Supplementary_Figure_S7A_EpilepsyScore_vs_SynapseScore.png")
)

p_glia <- plot_continuous(
  module_df,
  "GliaScore",
  "Glia-associated module score",
  "MTG AD: EpilepsyScore vs glia-associated module score",
  file.path(dir_results, "Supplementary_Figure_S7B_EpilepsyScore_vs_GliaScore.png")
)

p_balance <- plot_continuous(
  module_df,
  "SynGliaBalance",
  "Synapse-glia balance score",
  "MTG AD: EpilepsyScore vs synapse-glia balance",
  file.path(dir_results, "Supplementary_Figure_S7C_EpilepsyScore_vs_SynGliaBalance.png")
)

message("MTG continuous synapse-glia module analysis completed.")
