# =========================================================
# 07_generate_figures_and_supplementary_tables.R
# Purpose:
# Organize output files, generate source-data manifest,
# export package/session information, and optionally combine
# available source tables into a supplementary workbook.
# =========================================================

source("scripts/00_setup.R")

# -------------------------
# Optional package
# -------------------------
has_openxlsx <- requireNamespace("openxlsx", quietly = TRUE)

# -------------------------
# Step 1. Export R session information
# -------------------------
session_file <- file.path(proj_dir, "package_versions.txt")

writeLines(
  capture.output(sessionInfo()),
  con = session_file
)

message("Session information exported to: ", session_file)

# -------------------------
# Step 2. Define expected source outputs
# -------------------------
expected_files <- data.frame(
  Category = c(
    "Signature",
    "GSE5281 projection",
    "GSE5281 projection",
    "GSE5281 projection",
    "MTG analysis",
    "MTG analysis",
    "Sensitivity",
    "Sensitivity",
    "Singscore robustness",
    "Singscore robustness",
    "MTG continuous analysis",
    "MTG continuous analysis",
    "External evaluation",
    "External evaluation"
  ),
  File = c(
    "GSE268714_directional_signature_top100.csv",
    "GSE5281_EpilepsyScore_top100.csv",
    "GSE5281_region_wise_EpilepsyScore_comparison.csv",
    "GSE5281_linear_model_summary.txt",
    "GSE5281_MTG_AD_high_low_metadata.csv",
    "GSE5281_MTG_AD_high_vs_low_limma_results.csv",
    "GSE5281_signature_size_overall_sensitivity.csv",
    "GSE5281_signature_size_region_wise_sensitivity.csv",
    "GSE5281_ssGSEA_vs_singscore_correlation.csv",
    "GSE5281_singscore_direction_consistency.csv",
    "Supplementary_Table_S12_MTG_continuous_module_analysis.csv",
    "MTG_continuous_analysis_matched_module_genes.csv",
    "GSE132903_external_MTG_summary.csv",
    "GSE48350_dependence_aware_sensitivity.csv"
  ),
  Location = c(
    rep("results/source_tables", 14)
  ),
  stringsAsFactors = FALSE
)

expected_files$Path <- file.path(
  proj_dir,
  expected_files$Location,
  expected_files$File
)

expected_files$Available <- file.exists(expected_files$Path)

write.csv(
  expected_files,
  file = file.path(dir_results, "expected_output_file_manifest.csv"),
  row.names = FALSE
)

message("Expected output manifest exported.")

# -------------------------
# Step 3. Index all available result/source files
# -------------------------
all_result_files <- list.files(
  dir_results,
  recursive = TRUE,
  full.names = TRUE
)

file_index <- data.frame(
  File = basename(all_result_files),
  RelativePath = gsub(
    paste0(normalizePath(proj_dir, winslash = "/"), "/"),
    "",
    normalizePath(all_result_files, winslash = "/")
  ),
  SizeBytes = file.info(all_result_files)$size,
  stringsAsFactors = FALSE
)

write.csv(
  file_index,
  file = file.path(dir_results, "available_output_file_index.csv"),
  row.names = FALSE
)

message("Available output file index exported.")

# -------------------------
# Step 4. Create a README for result files
# -------------------------
results_readme <- c(
  "# Results",
  "",
  "This folder contains source tables, figure source data, and analysis outputs generated by the scripts.",
  "",
  "Key subfolders:",
  "",
  "- `source_tables/`: tabular outputs used for main and supplementary analyses.",
  "- `figure_source_data/`: source data used to generate figures.",
  "",
  "The file `expected_output_file_manifest.csv` lists expected analysis outputs and whether they are available.",
  "The file `available_output_file_index.csv` lists all currently available result files.",
  "",
  "Large raw GEO data files are not included in this repository and should be downloaded directly from GEO."
)

writeLines(
  results_readme,
  con = file.path(dir_results, "README_results.md")
)

message("Results README generated.")

# -------------------------
# Step 5. Optional: combine available CSV source tables into one workbook
# -------------------------
if (has_openxlsx) {
  
  library(openxlsx)
  
  csv_files <- list.files(
    dir_tables,
    pattern = "\\.csv$",
    full.names = TRUE
  )
  
  if (length(csv_files) > 0) {
    
    wb <- createWorkbook()
    
    for (f in csv_files) {
      df <- tryCatch(
        read.csv(f, check.names = FALSE, stringsAsFactors = FALSE),
        error = function(e) NULL
      )
      
      if (is.null(df)) next
      
      sheet_name <- tools::file_path_sans_ext(basename(f))
      sheet_name <- substr(sheet_name, 1, 31)
      sheet_name <- gsub("[\\[\\]\\*\\?/\\\\:]", "_", sheet_name)
      
      # avoid duplicated sheet names
      original_sheet_name <- sheet_name
      i <- 1
      while (sheet_name %in% names(wb)) {
        suffix <- paste0("_", i)
        sheet_name <- substr(
          paste0(substr(original_sheet_name, 1, 31 - nchar(suffix)), suffix),
          1,
          31
        )
        i <- i + 1
      }
      
      addWorksheet(wb, sheet_name)
      writeData(wb, sheet_name, df)
      setColWidths(wb, sheet_name, cols = 1:ncol(df), widths = "auto")
    }
    
    workbook_file <- file.path(
      dir_results,
      "combined_source_tables.xlsx"
    )
    
    saveWorkbook(wb, workbook_file, overwrite = TRUE)
    
    message("Combined source table workbook exported to: ", workbook_file)
    
  } else {
    message("No CSV files found in results/source_tables; workbook not generated.")
  }
  
} else {
  message("Package openxlsx is not installed; combined workbook was skipped.")
}

# -------------------------
# Step 6. Final message
# -------------------------
message("Output organization completed.")
